server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location ~ ^/(map|favorites|cabinet|profile|auth|post|chat)(/.*)?$ {
        try_files /index.html =404;
    }

    location ~ ^/(listing|legal)(/.*)?$ {
        try_files /index.html =404;
    }

    location = / {
        try_files /index.html =404;
    }

    location / {
        try_files $uri $uri/ =404;
    }

    error_page 404 /index.html;
}
