export const COUNTRIES = [
  { code: 'AM', cc: '374', ru: 'Армения', hy: 'Հայաստան', en: 'Armenia', min: 8, max: 8 },
  { code: 'RU', cc: '7', ru: 'Россия', hy: 'Ռուսաստան', en: 'Russia', min: 10, max: 10 },
  { code: 'GE', cc: '995', ru: 'Грузия', hy: 'Վրաստան', en: 'Georgia', min: 9, max: 9 },
  { code: 'AZ', cc: '994', ru: 'Азербайджан', hy: 'Ադրբեջան', en: 'Azerbaijan', min: 9, max: 9 },
  { code: 'BY', cc: '375', ru: 'Беларусь', hy: 'Բելառուս', en: 'Belarus', min: 9, max: 9 },
  { code: 'UA', cc: '380', ru: 'Украина', hy: 'Ուկրաինա', en: 'Ukraine', min: 9, max: 9 },
  { code: 'KZ', cc: '7', ru: 'Казахстан', hy: 'Ղազախստան', en: 'Kazakhstan', min: 10, max: 10 },
  { code: 'UZ', cc: '998', ru: 'Узбекистан', hy: 'Ուզբեկստան', en: 'Uzbekistan', min: 9, max: 9 },
  { code: 'KG', cc: '996', ru: 'Киргизия', hy: 'Ղրղզստան', en: 'Kyrgyzstan', min: 9, max: 9 },
  { code: 'TJ', cc: '992', ru: 'Таджикистан', hy: 'Տաջիկստան', en: 'Tajikistan', min: 9, max: 9 },
  { code: 'TM', cc: '993', ru: 'Туркменистан', hy: 'Թուրքմենստան', en: 'Turkmenistan', min: 8, max: 8 },
  { code: 'MD', cc: '373', ru: 'Молдова', hy: 'Մոլդովա', en: 'Moldova', min: 8, max: 8 },
  { code: 'US', cc: '1', ru: 'США', hy: 'ԱՄՆ', en: 'United States', min: 10, max: 10 },
  { code: 'CA', cc: '1', ru: 'Канада', hy: 'Կանադա', en: 'Canada', min: 10, max: 10 },
  { code: 'GB', cc: '44', ru: 'Великобритания', hy: 'Մեծ Բրիտանիա', en: 'United Kingdom', min: 10, max: 10 },
  { code: 'IE', cc: '353', ru: 'Ирландия', hy: 'Իռլանդիա', en: 'Ireland', min: 9, max: 9 },
  { code: 'FR', cc: '33', ru: 'Франция', hy: 'Ֆրանսիա', en: 'France', min: 9, max: 9 },
  { code: 'DE', cc: '49', ru: 'Германия', hy: 'Գերմանիա', en: 'Germany', min: 10, max: 11 },
  { code: 'ES', cc: '34', ru: 'Испания', hy: 'Իսպանիա', en: 'Spain', min: 9, max: 9 },
  { code: 'PT', cc: '351', ru: 'Португалия', hy: 'Պորտուգալիա', en: 'Portugal', min: 9, max: 9 },
  { code: 'IT', cc: '39', ru: 'Италия', hy: 'Իտալիա', en: 'Italy', min: 9, max: 10 },
  { code: 'NL', cc: '31', ru: 'Нидерланды', hy: 'Նիդերլանդներ', en: 'Netherlands', min: 9, max: 9 },
  { code: 'BE', cc: '32', ru: 'Бельгия', hy: 'Բելգիա', en: 'Belgium', min: 9, max: 9 },
  { code: 'LU', cc: '352', ru: 'Люксембург', hy: 'Լյուքսեմբուրգ', en: 'Luxembourg', min: 8, max: 9 },
  { code: 'CH', cc: '41', ru: 'Швейцария', hy: 'Շվեյցարիա', en: 'Switzerland', min: 9, max: 9 },
  { code: 'AT', cc: '43', ru: 'Австрия', hy: 'Ավստրիա', en: 'Austria', min: 9, max: 11 },
  { code: 'PL', cc: '48', ru: 'Польша', hy: 'Լեհաստան', en: 'Poland', min: 9, max: 9 },
  { code: 'CZ', cc: '420', ru: 'Чехия', hy: 'Չեխիա', en: 'Czechia', min: 9, max: 9 },
  { code: 'SK', cc: '421', ru: 'Словакия', hy: 'Սլովակիա', en: 'Slovakia', min: 9, max: 9 },
  { code: 'HU', cc: '36', ru: 'Венгрия', hy: 'Հունգարիա', en: 'Hungary', min: 8, max: 9 },
  { code: 'RO', cc: '40', ru: 'Румыния', hy: 'Ռումինիա', en: 'Romania', min: 9, max: 9 },
  { code: 'BG', cc: '359', ru: 'Болгария', hy: 'Բուլղարիա', en: 'Bulgaria', min: 8, max: 9 },
  { code: 'GR', cc: '30', ru: 'Греция', hy: 'Հունաստան', en: 'Greece', min: 10, max: 10 },
  { code: 'CY', cc: '357', ru: 'Кипр', hy: 'Կիպրոս', en: 'Cyprus', min: 8, max: 8 },
  { code: 'MT', cc: '356', ru: 'Мальта', hy: 'Մալթա', en: 'Malta', min: 8, max: 8 },
  { code: 'HR', cc: '385', ru: 'Хорватия', hy: 'Խորվաթիա', en: 'Croatia', min: 8, max: 9 },
  { code: 'SI', cc: '386', ru: 'Словения', hy: 'Սլովենիա', en: 'Slovenia', min: 8, max: 8 },
  { code: 'RS', cc: '381', ru: 'Сербия', hy: 'Սերբիա', en: 'Serbia', min: 8, max: 9 },
  { code: 'BA', cc: '387', ru: 'Босния и Герцеговина', hy: 'Բոսնիա և Հերցեգովինա', en: 'Bosnia and Herzegovina', min: 8, max: 9 },
  { code: 'ME', cc: '382', ru: 'Черногория', hy: 'Չեռնոգորիա', en: 'Montenegro', min: 8, max: 9 },
  { code: 'MK', cc: '389', ru: 'Северная Македония', hy: 'Հյուսիսային Մակեդոնիա', en: 'North Macedonia', min: 8, max: 8 },
  { code: 'AL', cc: '355', ru: 'Албания', hy: 'Ալբանիա', en: 'Albania', min: 9, max: 9 },
  { code: 'XK', cc: '383', ru: 'Косово', hy: 'Կոսովո', en: 'Kosovo', min: 8, max: 8 },
  { code: 'LT', cc: '370', ru: 'Литва', hy: 'Լիտվա', en: 'Lithuania', min: 8, max: 8 },
  { code: 'LV', cc: '371', ru: 'Латвия', hy: 'Լատվիա', en: 'Latvia', min: 8, max: 8 },
  { code: 'EE', cc: '372', ru: 'Эстония', hy: 'Էստոնիա', en: 'Estonia', min: 7, max: 8 },
  { code: 'FI', cc: '358', ru: 'Финляндия', hy: 'Ֆինլանդիա', en: 'Finland', min: 9, max: 10 },
  { code: 'SE', cc: '46', ru: 'Швеция', hy: 'Շվեդիա', en: 'Sweden', min: 9, max: 9 },
  { code: 'NO', cc: '47', ru: 'Норвегия', hy: 'Նորվեգիա', en: 'Norway', min: 8, max: 8 },
  { code: 'DK', cc: '45', ru: 'Дания', hy: 'Դանիա', en: 'Denmark', min: 8, max: 8 },
  { code: 'IS', cc: '354', ru: 'Исландия', hy: 'Իսլանդիա', en: 'Iceland', min: 7, max: 7 },
  { code: 'TR', cc: '90', ru: 'Турция', hy: 'Թուրքիա', en: 'Turkey', min: 10, max: 10 },
  { code: 'IL', cc: '972', ru: 'Израиль', hy: 'Իսրայել', en: 'Israel', min: 9, max: 9 },
  { code: 'PS', cc: '970', ru: 'Палестина', hy: 'Պաղեստին', en: 'Palestine', min: 9, max: 9 },
  { code: 'JO', cc: '962', ru: 'Иордания', hy: 'Հորդանան', en: 'Jordan', min: 9, max: 9 },
  { code: 'LB', cc: '961', ru: 'Ливан', hy: 'Լիբանան', en: 'Lebanon', min: 7, max: 8 },
  { code: 'SY', cc: '963', ru: 'Сирия', hy: 'Սիրիա', en: 'Syria', min: 9, max: 9 },
  { code: 'IQ', cc: '964', ru: 'Ирак', hy: 'Իրաք', en: 'Iraq', min: 10, max: 10 },
  { code: 'IR', cc: '98', ru: 'Иран', hy: 'Իրան', en: 'Iran', min: 10, max: 10 },
  { code: 'SA', cc: '966', ru: 'Саудовская Аравия', hy: 'Սաուդյան Արաբիա', en: 'Saudi Arabia', min: 9, max: 9 },
  { code: 'AE', cc: '971', ru: 'ОАЭ', hy: 'ԱՄԷ', en: 'United Arab Emirates', min: 9, max: 9 },
  { code: 'QA', cc: '974', ru: 'Катар', hy: 'Կատար', en: 'Qatar', min: 8, max: 8 },
  { code: 'KW', cc: '965', ru: 'Кувейт', hy: 'Քուվեյթ', en: 'Kuwait', min: 8, max: 8 },
  { code: 'BH', cc: '973', ru: 'Бахрейн', hy: 'Բահրեյն', en: 'Bahrain', min: 8, max: 8 },
  { code: 'OM', cc: '968', ru: 'Оман', hy: 'Օման', en: 'Oman', min: 8, max: 8 },
  { code: 'YE', cc: '967', ru: 'Йемен', hy: 'Եմեն', en: 'Yemen', min: 9, max: 9 },
  { code: 'EG', cc: '20', ru: 'Египет', hy: 'Եգիպտոս', en: 'Egypt', min: 10, max: 10 },
  { code: 'MA', cc: '212', ru: 'Марокко', hy: 'Մարոկկո', en: 'Morocco', min: 9, max: 9 },
  { code: 'DZ', cc: '213', ru: 'Алжир', hy: 'Ալժիր', en: 'Algeria', min: 9, max: 9 },
  { code: 'TN', cc: '216', ru: 'Тунис', hy: 'Թունիս', en: 'Tunisia', min: 8, max: 8 },
  { code: 'LY', cc: '218', ru: 'Ливия', hy: 'Լիբիա', en: 'Libya', min: 9, max: 9 },
  { code: 'CN', cc: '86', ru: 'Китай', hy: 'Չինաստան', en: 'China', min: 11, max: 11 },
  { code: 'HK', cc: '852', ru: 'Гонконг', hy: 'Հոնկոնգ', en: 'Hong Kong', min: 8, max: 8 },
  { code: 'MO', cc: '853', ru: 'Макао', hy: 'Մակաո', en: 'Macau', min: 8, max: 8 },
  { code: 'TW', cc: '886', ru: 'Тайвань', hy: 'Թայվան', en: 'Taiwan', min: 9, max: 9 },
  { code: 'JP', cc: '81', ru: 'Япония', hy: 'Ճապոնիա', en: 'Japan', min: 10, max: 10 },
  { code: 'KR', cc: '82', ru: 'Южная Корея', hy: 'Հարավային Կորեա', en: 'South Korea', min: 9, max: 10 },
  { code: 'KP', cc: '850', ru: 'Северная Корея', hy: 'Հյուսիսային Կորեա', en: 'North Korea', min: 8, max: 10 },
  { code: 'MN', cc: '976', ru: 'Монголия', hy: 'Մոնղոլիա', en: 'Mongolia', min: 8, max: 8 },
  { code: 'IN', cc: '91', ru: 'Индия', hy: 'Հնդկաստան', en: 'India', min: 10, max: 10 },
  { code: 'PK', cc: '92', ru: 'Пакистан', hy: 'Պակիստան', en: 'Pakistan', min: 10, max: 10 },
  { code: 'BD', cc: '880', ru: 'Бангладеш', hy: 'Բանգլադեշ', en: 'Bangladesh', min: 10, max: 10 },
  { code: 'LK', cc: '94', ru: 'Шри-Ланка', hy: 'Շրի Լանկա', en: 'Sri Lanka', min: 9, max: 9 },
  { code: 'NP', cc: '977', ru: 'Непал', hy: 'Նեպալ', en: 'Nepal', min: 10, max: 10 },
  { code: 'AF', cc: '93', ru: 'Афганистан', hy: 'Աֆղանստան', en: 'Afghanistan', min: 9, max: 9 },
  { code: 'MM', cc: '95', ru: 'Мьянма', hy: 'Մյանմա', en: 'Myanmar', min: 8, max: 10 },
  { code: 'TH', cc: '66', ru: 'Таиланд', hy: 'Թաիլանդ', en: 'Thailand', min: 9, max: 9 },
  { code: 'VN', cc: '84', ru: 'Вьетнам', hy: 'Վիետնամ', en: 'Vietnam', min: 9, max: 9 },
  { code: 'KH', cc: '855', ru: 'Камбоджа', hy: 'Կամբոջա', en: 'Cambodia', min: 8, max: 9 },
  { code: 'LA', cc: '856', ru: 'Лаос', hy: 'Լաոս', en: 'Laos', min: 9, max: 10 },
  { code: 'MY', cc: '60', ru: 'Малайзия', hy: 'Մալայզիա', en: 'Malaysia', min: 9, max: 10 },
  { code: 'SG', cc: '65', ru: 'Сингапур', hy: 'Սինգապուր', en: 'Singapore', min: 8, max: 8 },
  { code: 'ID', cc: '62', ru: 'Индонезия', hy: 'Ինդոնեզիա', en: 'Indonesia', min: 9, max: 11 },
  { code: 'PH', cc: '63', ru: 'Филиппины', hy: 'Ֆիլիպիններ', en: 'Philippines', min: 10, max: 10 },
  { code: 'AU', cc: '61', ru: 'Австралия', hy: 'Ավստրալիա', en: 'Australia', min: 9, max: 9 },
  { code: 'NZ', cc: '64', ru: 'Новая Зеландия', hy: 'Նոր Զելանդիա', en: 'New Zealand', min: 8, max: 9 },
  { code: 'ZA', cc: '27', ru: 'ЮАР', hy: 'ՀԱՀ', en: 'South Africa', min: 9, max: 9 },
  { code: 'NG', cc: '234', ru: 'Нигерия', hy: 'Նիգերիա', en: 'Nigeria', min: 10, max: 10 },
  { code: 'KE', cc: '254', ru: 'Кения', hy: 'Քենիա', en: 'Kenya', min: 9, max: 9 },
  { code: 'ET', cc: '251', ru: 'Эфиопия', hy: 'Եթովպիա', en: 'Ethiopia', min: 9, max: 9 },
  { code: 'GH', cc: '233', ru: 'Гана', hy: 'Գանա', en: 'Ghana', min: 9, max: 9 },
  { code: 'TZ', cc: '255', ru: 'Танзания', hy: 'Տանզանիա', en: 'Tanzania', min: 9, max: 9 },
  { code: 'UG', cc: '256', ru: 'Уганда', hy: 'Ուգանդա', en: 'Uganda', min: 9, max: 9 },
  { code: 'CM', cc: '237', ru: 'Камерун', hy: 'Կամերուն', en: 'Cameroon', min: 9, max: 9 },
  { code: 'CI', cc: '225', ru: 'Кот-д’Ивуар', hy: 'Կոտ դ’Իվուար', en: 'Ivory Coast', min: 8, max: 10 },
  { code: 'SN', cc: '221', ru: 'Сенегал', hy: 'Սենեգալ', en: 'Senegal', min: 9, max: 9 },
  { code: 'MZ', cc: '258', ru: 'Мозамбик', hy: 'Մոզամբիկ', en: 'Mozambique', min: 9, max: 9 },
  { code: 'AO', cc: '244', ru: 'Ангола', hy: 'Անգոլա', en: 'Angola', min: 9, max: 9 },
  { code: 'ZM', cc: '260', ru: 'Замбия', hy: 'Զամբիա', en: 'Zambia', min: 9, max: 9 },
  { code: 'ZW', cc: '263', ru: 'Зимбабве', hy: 'Զիմբաբվե', en: 'Zimbabwe', min: 9, max: 9 },
  { code: 'MG', cc: '261', ru: 'Мадагаскар', hy: 'Մադագասկար', en: 'Madagascar', min: 9, max: 9 },
  { code: 'MU', cc: '230', ru: 'Маврикий', hy: 'Մավրիկիոս', en: 'Mauritius', min: 7, max: 8 },
  { code: 'MX', cc: '52', ru: 'Мексика', hy: 'Մեքսիկա', en: 'Mexico', min: 10, max: 10 },
  { code: 'BR', cc: '55', ru: 'Бразилия', hy: 'Բրազիլիա', en: 'Brazil', min: 10, max: 11 },
  { code: 'AR', cc: '54', ru: 'Аргентина', hy: 'Արգենտինա', en: 'Argentina', min: 10, max: 11 },
  { code: 'CL', cc: '56', ru: 'Чили', hy: 'Չիլի', en: 'Chile', min: 9, max: 9 },
  { code: 'CO', cc: '57', ru: 'Колумбия', hy: 'Կոլումբիա', en: 'Colombia', min: 10, max: 10 },
  { code: 'PE', cc: '51', ru: 'Перу', hy: 'Պերու', en: 'Peru', min: 9, max: 9 },
  { code: 'VE', cc: '58', ru: 'Венесуэла', hy: 'Վենեսուելա', en: 'Venezuela', min: 10, max: 10 },
  { code: 'EC', cc: '593', ru: 'Эквадор', hy: 'Էկվադոր', en: 'Ecuador', min: 9, max: 9 },
  { code: 'BO', cc: '591', ru: 'Боливия', hy: 'Բոլիվիա', en: 'Bolivia', min: 8, max: 8 },
  { code: 'PY', cc: '595', ru: 'Парагвай', hy: 'Պարագվայ', en: 'Paraguay', min: 9, max: 9 },
  { code: 'UY', cc: '598', ru: 'Уругвай', hy: 'Ուրուգվայ', en: 'Uruguay', min: 8, max: 9 },
  { code: 'CR', cc: '506', ru: 'Коста-Рика', hy: 'Կոստա Ռիկա', en: 'Costa Rica', min: 8, max: 8 },
  { code: 'PA', cc: '507', ru: 'Панама', hy: 'Պանամա', en: 'Panama', min: 8, max: 8 },
  { code: 'GT', cc: '502', ru: 'Гватемала', hy: 'Գվատեմալա', en: 'Guatemala', min: 8, max: 8 },
  { code: 'HN', cc: '504', ru: 'Гондурас', hy: 'Հոնդուրաս', en: 'Honduras', min: 8, max: 8 },
  { code: 'SV', cc: '503', ru: 'Сальвадор', hy: 'Սալվադոր', en: 'El Salvador', min: 8, max: 8 },
  { code: 'NI', cc: '505', ru: 'Никарагуа', hy: 'Նիկարագուա', en: 'Nicaragua', min: 8, max: 8 },
  { code: 'DO', cc: '1', ru: 'Доминиканская Республика', hy: 'Դոմինիկյան Հանրապետություն', en: 'Dominican Republic', min: 10, max: 10 },
  { code: 'CU', cc: '53', ru: 'Куба', hy: 'Կուբա', en: 'Cuba', min: 8, max: 8 },
  { code: 'JM', cc: '1', ru: 'Ямайка', hy: 'Ջամայկա', en: 'Jamaica', min: 10, max: 10 },
  { code: 'PR', cc: '1', ru: 'Пуэрто-Рико', hy: 'Պուերտո Ռիկո', en: 'Puerto Rico', min: 10, max: 10 }
];

export function findCountry(code) {
  return COUNTRIES.find((c) => c.code === code) || COUNTRIES[0];
}

export function findCountryByDigits(digits) {
  let best = null;
  for (const c of COUNTRIES) {
    if (digits.startsWith(c.cc) && (!best || c.cc.length > best.cc.length)) best = c;
  }
  return best;
}

export function groupDigits(digits) {
  return (digits.match(/.{1,3}/g) || []).join(' ');
}
